# Generated by Django 4.1.3 on 2024-01-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhpawapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
    ]
