# Generated by Django 4.1.3 on 2024-01-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhpawapi', '0002_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='order_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='revenue',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
