# Generated by Django 4.1.3 on 2024-01-10 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhpawapi', '0003_alter_revenue_order_amount_alter_revenue_tip_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
