# Generated by Django 4.1.3 on 2024-01-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhpawapi', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revenue',
            name='date',
            field=models.DateField(),
        ),
    ]
